### ISSUE TITLE
Json logging notifies SyslogClockOrTimezoneWrong

### ISSUE THREAD

**Issue by hanjukim** [winstonjs/node-loggly#43]
I'm using winston-loggly to send logs to Loggly.
Every log with json.true option give me following notification:

LogglyNotifications:
[0]:
message: Timestamp field extracted from Syslog header is missing TZ
type: SyslogClockOrTimezoneWrong

I have succeeded to fix this issue by overriding message.timestamp at Loggly.prototype.log, but I think this was not ultimate solution.

**Comment by GunnarLindholm** [comment]
Could you show more in detail what you did? What is the new code you are using?
